### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by ZSimon** [MewsSystems/fiscalization-hungary#60]
Hi,

there is some problem with sending request to authorities.

When I try to get the exchange token:
`var exchangeToken = await navClient.GetExchangeTokenAsync();`
it works on client machine(Windows10) from visual studio or from my COM interop dll.

When I try to execute it on the server (Windows2012), I get this error:
"The request was aborted: Could not create SSL/TLS secure channel"

And in event viewer on the server there is error:
"A fatal alert was received from the remote endpoint. The TLS protocol defined fatal alert code is 40."

Any idea what it could be? I have the latest NET framework installed on server.

Thanks, Simon

**Comment by KaliCZ** [comment]
Hey, sorry but it's kinda hard for me to troubleshoot that. Perhaps the TLS dependencies are defined in some older NET Framework package than the one you installed, but then you would see a crash rather than a failure to create TLS channel.

We know it works when you host this in Azure Apps and as you said, it works locally for you as well. So that looks like an issue with your virtual machine. Not much I can tell you here :(

**Comment by ZSimon** [comment]
Requested TLS protocol is TLS12, but some clients try to connect different.

`I have included this line into code:
        internal Client(HttpClient httpClient, NavEnvironment environment)
        {
            HttpClient = httpClient;
            Environment = environment;
            **System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;**
        }

And now it works everywhere and in all situations.` If somebody else will have problems.

**Comment by KaliCZ** [comment]
@ZSimon Alright, thx for fixing. Will you open a PR to the repo with this? So you're forever marked as a contributor :)

**Comment by ZSimon** [comment]
Thanks. I will do today or tomorrow - I must first read more about how to
do that since it would be my first PR :)

Do you maybe know how customerinfo can be required if there are most of the
shops without having customer address and tax number?
https://github.com/MewsSystems/fiscalization-hungary/issues/61

I think it is not logical. I have also commented on github, hoping
abdall will dig more into it. Can you ask him?

Thank you,
Simon

**Comment by KaliCZ** [comment]
Actually, now looking at [the PR](https://github.com/MewsSystems/fiscalization-hungary/pull/62), since it's a static property, this could potentially break network communications in the app using this nuget package. Therefore this setting should not be set from inside this package. This should be set in the master application. So whatever is the application you're creating 
- Console application
- ASP server
- API
- Winform/WPF application
This setting should be there. Because when you write an application and use a fiscalization Nuget package, you don't expect it to set TLS version for all network communications.
