### ISSUE TITLE
Product reclamation

### ISSUE THREAD

**Issue by ZSimon** [MewsSystems/fiscalization-hungary#64]
Hi,
I have one question, how do you deal with reclamations? 
The customer buys for example 2 products and you issue an invoice. Then the next day the customer returns them back(reclamation). I can probably call SendCorrectionInvoice and both items with negative quantities something like in your example: 
`            return new ModificationInvoice(
                number: InvoiceNumber.Create("ABC-18abfcefsaa").Success.Get(),
                supplierInfo: GetSupplierInfo(),
                customerInfo: GetCustomerInfo(),
                items: Sequence.FromPreordered(new[] { item, item1 }, startIndex: 1).Get(),
                currencyCode: CurrencyCode.Create("USD").Success.Get(),
                issueDate: new DateTime(2020, 08, 31),
                paymentDate: new DateTime(2020, 08, 31),
                itemIndexOffset: 4,
                modificationIndex: 4,
                modifyWithoutMaster: true,
                originalDocumentNumber: InvoiceNumber.Create("ABC-18afasadafa").Success.Get()
            );`

But I'm not sure what is this in case when you return all items(or modify all items):                
itemIndexOffset: 4,
modificationIndex: 4,

You modify in fact all lines, lets say index 1 and 2. What should be the modification index in this case?

Thank you, Simon

**Comment by KaliCZ** [comment]
Hey, you're correct. When you have an invoice with 2 items and you return one, essentially what you're doing is that you'll send a modification invoice with 
- `modificationIndex: 1` because the index of this bill is 1 - zero being the original
- `itemIndexOffset: 2` because there are now 2 items already reported in this bill chain. 

And you put the item you return in negative. You can also put another positive items on this modification. Keep in mind you are still technically modifying the same invoice, so you can then return the `another positive item on this modification`. 

If you were to return the `another positive item on this modification`, then the third request would be: 
- `modificationIndex: 2` because the index of this bill is 2 - zero being the original, one being the first modification
- `itemIndexOffset: 4` because there are items reported in the original and another 2 reported in the first modification.
